import { useState, useRef, useEffect } from "react";
import { motion } from "framer-motion";
import { Bot, Send, User, Sparkles, AlertTriangle, TrendingUp, PieChart as PieChartIcon, Activity } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { usePortfolio } from "@/hooks/usePortfolio";

interface Message {
  role: "user" | "assistant";
  content: string; // Will store the raw JSON string if it's the assistant
}

interface StructuredAdvisorResponse {
  summary: string;
  risk_analysis: string;
  strategy: string;
  confidence: string;
}

const suggestedQuestions = [
  "Analyze my portfolio beta and risk limits",
  "Simulate rebalancing to target a 0.8 beta",
  "What is my highest concentration risk?",
  "Suggest hedges for my tech overexposure",
  "Calculate my weighted sector exposure",
];

const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";

const container = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.05 } } };
const item = { hidden: { opacity: 0, y: 10 }, show: { opacity: 1, y: 0 } };

export default function AIAdvisor() {
  const { user } = useAuth();
  const { data: portfolio } = usePortfolio();
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages]);

  const [activeContextDisplay, setActiveContextDisplay] = useState<any>(null);

  // --- Calculate Math Context for the AI ---
  const generateContextObject = () => {
    if (!portfolio || portfolio.holdings.length === 0) return null;

    // Simulate beta values for demo (in production, fetch real beta per symbol)
    const mockBetas: Record<string, number> = { AAPL: 1.2, TSLA: 2.1, MSFT: 1.1, NVDA: 1.8, default: 1.0 };

    let weightedBetaSum = 0;
    const sectorWeights: Record<string, number> = {};
    const topHoldings = portfolio.allocations.slice(0, 3).map(a => {
      const beta = mockBetas[a.symbol] || mockBetas.default;
      // Weight is represented as a decimal (e.g., 0.25)
      const weight = a.pct / 100;
      weightedBetaSum += (weight * beta);

      sectorWeights[a.sector] = (sectorWeights[a.sector] || 0) + a.pct;

      return { symbol: a.symbol, allocation: a.pct.toFixed(1), beta };
    });

    const portfolio_beta = weightedBetaSum.toFixed(2);
    const sector_exposure = Object.entries(sectorWeights).map(([s, w]) => `${s}: ${w.toFixed(1)}%`);
    const volatility = (parseFloat(portfolio_beta) > 1.2) ? "High" : "Moderate";
    const sharpe_ratio = (portfolio.diversificationScore > 75) ? "1.4 (Est)" : "0.9 (Est)";
    const news_sentiment_score = "Mixed to Bullish (Simulated pending News integration)";
    const prediction_confidence = "75% (Simulated prediction engine metric)";

    // Simulate sector sentiments generated by the News Intelligence module
    // In production, sync this state directly from the News context
    const sector_sentiment = {
      "Technology": -0.7,
      "Banking": 0.4,
      "Energy": 0.1,
      "Auto": -0.2,
      "Pharma": 0.6
    };

    // Construct the structured JSON block the backend requested
    return {
      portfolio_beta,
      sector_exposure,
      top_holdings: topHoldings,
      volatility,
      sharpe_ratio,
      risk_score: `${portfolio.riskScore.toFixed(1)}/3.0`,
      news_sentiment_score,
      prediction_confidence,
      sector_sentiment,
      total_portfolio_value: `$${portfolio.totalInvestment.toLocaleString()}`
    };
  };

  const sendMessage = async (text: string) => {
    if (!text.trim() || isTyping) return;
    const userMsg: Message = { role: "user", content: text };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsTyping(true);

    const contextObj = generateContextObject();
    setActiveContextDisplay(contextObj);
    const portfolioContextValue = contextObj ? JSON.stringify(contextObj, null, 2) : "\n\nUser has no portfolio data imported yet.";

    const systemOverride: Message = {
      role: "assistant",
      content: `SYSTEM RULE: You MUST output your response as a valid JSON object matching this exact schema: {"summary": "Brief 2-3 sentence overview","risk_analysis": "Detailed explanation","strategy": "Actionable recommendation","confidence": "High/Medium/Low"}. Keep your outputs purely analytical and structurally compliant. Return ONLY valid JSON.`
    };

    const allMessages = [systemOverride, ...messages, userMsg].filter(m => m.content);

    const groqKey = import.meta.env.VITE_GROQ_API_KEY;
    console.log("[AI Advisor] Groq key present:", !!groqKey, "Key prefix:", groqKey?.slice(0, 8));

    try {
      if (!groqKey) throw new Error("VITE_GROQ_API_KEY not set in .env — please restart the dev server after adding it");

      const resp = await fetch(GROQ_URL, {
        method: "POST",
        headers: { Authorization: `Bearer ${groqKey}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "llama-3.1-8b-instant",
          messages: allMessages.map(m => ({ role: m.role, content: m.content })),
          temperature: 0.2,
        }),
      });

      if (!resp.ok) {
        const errText = await resp.text();
        console.error("[AI Advisor] Groq API error response:", resp.status, errText);
        throw new Error(`Groq error ${resp.status}: ${errText.slice(0, 200)}`);
      }

      const groqData = await resp.json();
      console.log("[AI Advisor] Groq response OK:", groqData.choices?.[0]?.finish_reason);
      const aiContent = groqData.choices?.[0]?.message?.content ?? "";
      const cleaned = aiContent.replace(/^```json\n?/gi, "").replace(/\n?```$/gi, "").trim();
      setMessages(prev => [...prev, { role: "assistant", content: cleaned }]);

    } catch (err: any) {
      console.error("[AI Advisor] Full error:", err);
      const ctx = contextObj;
      const fallback = JSON.stringify({
        summary: `Portfolio: ${ctx?.total_portfolio_value ?? "N/A"} | Beta: ${ctx?.portfolio_beta ?? "N/A"} | Risk: ${ctx?.risk_score ?? "N/A"}`,
        risk_analysis: `⚠️ AI call failed: ${err.message}. Sectors: ${(ctx?.sector_exposure ?? []).join(", ")}.`,
        strategy: "Review your highest-weight sector. Rebalance positions exceeding 30%.",
        confidence: "Low",
      });
      setMessages(prev => [...prev, { role: "assistant", content: fallback }]);
    } finally {
      setIsTyping(false);
    }
  };

  // Helper component to render the structured JSON
  const renderStructuredResponse = (jsonString: string) => {
    try {
      // Aggressively strip markdown JSON wrappers if present
      const cleanJson = jsonString.replace(/^```json\n?/g, "").replace(/\n?```$/g, "").trim();
      const data: StructuredAdvisorResponse = JSON.parse(cleanJson);

      // Handle case where it crashed or isn't formatted right
      if (!data.risk_analysis) {
        return <div className="text-sm">{data.summary || jsonString}</div>;
      }

      return (
        <div className="space-y-4">
          <p className="font-medium text-sm text-foreground/90">{data.summary}</p>

          {/* Analysis */}
          <div className="text-sm text-muted-foreground border-l-2 border-primary/30 pl-3 py-1">
            {data.risk_analysis}
          </div>

          {/* Strategy Section */}
          {(data.strategy || data.confidence) && (
            <div className="space-y-2 mt-4 bg-secondary/30 p-3 rounded-lg border border-border/50">
              <h4 className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wider text-primary">
                <TrendingUp className="w-3.5 h-3.5" /> Strategy & Confidence
              </h4>
              <div className="flex flex-col gap-2">
                {data.strategy && (
                  <p className="text-sm font-medium">{data.strategy}</p>
                )}
                {data.confidence && (
                  <p className="text-xs text-muted-foreground bg-background/50 inline-block px-2 py-1 rounded w-fit">
                    Confidence Level: <span className="font-bold">{data.confidence}</span>
                  </p>
                )}
              </div>
            </div>
          )}
        </div>
      );
    } catch (e) {
      // Fallback if parsing fails
      return <div className="text-sm whitespace-pre-wrap">{jsonString}</div>;
    }
  };

  return (
    <motion.div variants={container} initial="hidden" animate="show" className="flex flex-col h-[calc(100vh-3rem)]">
      <motion.div variants={item} className="mb-4">
        <h1 className="text-3xl font-bold flex items-center gap-3"><PieChartIcon className="w-8 h-8 text-primary" /> AI Quantitative Advisor</h1>
        <p className="text-muted-foreground mt-1">
          Structured financial reasoning engine powered by live calculations.
        </p>
      </motion.div>

      <div className="flex flex-1 gap-6 overflow-hidden">
        <motion.div variants={item} className="flex-1 flex flex-col glass-card overflow-hidden">
          <div ref={scrollRef} className="flex-1 overflow-y-auto p-4 space-y-4">
            {messages.length === 0 && (
              <div className="flex flex-col items-center justify-center h-full text-muted-foreground gap-4 opacity-50">
                <Bot className="w-12 h-12" />
                <p>Awaiting mathematical parameters or queries. Type below to run a simulation.</p>
              </div>
            )}

            {messages.map((msg, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                className={`flex gap-3 ${msg.role === "user" ? "justify-end" : ""}`}
              >
                {msg.role === "assistant" && (
                  <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0 mt-1">
                    <Bot className="w-4 h-4 text-primary" />
                  </div>
                )}
                <div className={`max-w-[75%] p-4 rounded-xl leading-relaxed ${msg.role === "user"
                  ? "bg-primary text-primary-foreground rounded-br-sm text-sm"
                  : "bg-secondary/30 border border-border/50 rounded-bl-sm"
                  }`}>
                  {msg.role === "assistant" ? renderStructuredResponse(msg.content) : <span>{msg.content}</span>}
                </div>
                {msg.role === "user" && (
                  <div className="w-8 h-8 rounded-lg bg-secondary flex items-center justify-center shrink-0 mt-1 border border-border">
                    <User className="w-4 h-4 text-foreground" />
                  </div>
                )}
              </motion.div>
            ))}
            {isTyping && !messages[messages.length - 1]?.content && (
              <div className="flex gap-3">
                <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                  <Bot className="w-4 h-4 text-primary" />
                </div>
                <div className="bg-secondary/50 border border-border/50 rounded-xl rounded-bl-sm p-4">
                  <div className="flex gap-1">
                    <div className="w-2 h-2 rounded-full bg-muted-foreground animate-pulse" />
                    <div className="w-2 h-2 rounded-full bg-muted-foreground animate-pulse" style={{ animationDelay: "0.2s" }} />
                    <div className="w-2 h-2 rounded-full bg-muted-foreground animate-pulse" style={{ animationDelay: "0.4s" }} />
                  </div>
                </div>
              </div>
            )}
          </div>

          {messages.length <= 1 && (
            <div className="px-4 pb-2">
              <div className="flex items-center gap-1 mb-2 text-xs text-muted-foreground">
                <Sparkles className="w-3 h-3" /> Suggested questions
              </div>
              <div className="flex flex-wrap gap-2">
                {suggestedQuestions.map((q) => (
                  <button
                    key={q}
                    onClick={() => sendMessage(q)}
                    className="text-xs px-3 py-1.5 rounded-full border border-border hover:border-primary/30 hover:bg-primary/5 text-muted-foreground hover:text-foreground transition-colors"
                  >
                    {q}
                  </button>
                ))}
              </div>
            </div>
          )}

          <div className="p-4 border-t border-border">
            <form onSubmit={(e) => { e.preventDefault(); sendMessage(input); }} className="flex gap-2">
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask about your portfolio, markets, or strategy..."
                className="flex-1 bg-secondary/50 border border-border rounded-xl px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-primary placeholder:text-muted-foreground"
              />
              <button
                type="submit"
                disabled={!input.trim() || isTyping}
                className="px-4 rounded-xl bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
              >
                <Send className="w-4 h-4" />
              </button>
            </form>
          </div>
        </motion.div>

        {activeContextDisplay && (
          <motion.div variants={item} className="hidden lg:flex w-80 flex-col glass-card overflow-hidden">
            <div className="p-4 border-b border-border/50 font-semibold flex items-center gap-2 text-sm bg-primary/5">
              <Activity className="w-4 h-4 text-primary" />
              AI Reasoning Source
            </div>
            <div className="p-4 overflow-y-auto space-y-5 text-sm">
              <div>
                <span className="text-muted-foreground flex items-center gap-1.5 text-xs mb-1 uppercase tracking-wider font-semibold">Portfolio Metrics</span>
                <div className="bg-secondary/30 rounded border border-border/50 divide-y divide-border/50 text-xs">
                  <div className="flex justify-between p-2"><span>Beta</span><span className="font-mono font-medium">{activeContextDisplay.portfolio_beta}</span></div>
                  <div className="flex justify-between p-2"><span>Risk Score</span><span className="font-mono font-medium">{activeContextDisplay.risk_score}</span></div>
                  <div className="flex justify-between p-2"><span>Volatility</span><span className="font-medium">{activeContextDisplay.volatility}</span></div>
                </div>
              </div>

              <div>
                <span className="text-muted-foreground flex items-center gap-1.5 text-xs mb-1 uppercase tracking-wider font-semibold">Sector Sentiments</span>
                <div className="space-y-1">
                  {Object.entries(activeContextDisplay.sector_sentiment).map(([k, v]: any) => (
                    <div key={k} className="flex justify-between items-center bg-secondary/30 p-1.5 px-2 rounded border border-border/30 text-xs">
                      <span>{k}</span>
                      <span className={v < 0 ? "text-destructive font-medium" : "text-emerald-500 font-medium"}>{v > 0 ? `+${v}` : v}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div>
                <span className="text-muted-foreground flex items-center gap-1.5 text-xs mb-1 uppercase tracking-wider font-semibold">Prediction Confidence</span>
                <span className="text-xs bg-primary/10 text-primary px-2 py-1.5 rounded block border border-primary/20">
                  {activeContextDisplay.prediction_confidence}
                </span>
              </div>
            </div>
          </motion.div>
        )}
      </div>
    </motion.div>
  );
}
